### ISSUE TITLE
Multijet Herwig vs P8 Comparison

### ISSUE THREAD

**Issue by lawrenceleejr** [lawrenceleejr/FragmentationStudy#10]
Looking to compare the Herwig and Pythia8 showering for the multijet ("Z+gluon" and "three jet") samples. The profiles qualitatively agree but we want to see how much the agree quantitatively.

**Comment by cbell1402** [comment]
![image](https://user-images.githubusercontent.com/93935192/212145026-d0091b35-c166-4cb8-b2ab-e13ab2754483.png)

**Comment by lawrenceleejr** [comment]
Interesting. So they actually really don't agree in the absolute number. But now that I understand what the herwig sample was a little better, maybe it's a process dependence and not a shower difference... But ok. Let's call this ticket closed. Thank you @cbell1402!
