### ISSUE TITLE
Remove gluon jets from analysis

### ISSUE THREAD

**Issue by lawrenceleejr** [lawrenceleejr/FragmentationStudy#11]
We want to ignore gluon jets in our jet-level analysis. We want to identify jets w/ a small deltaR (probably below 0.4) to an "initial" gluon.

We want to ask a jet, what is the parton (i.e. quark or gluon) that seems to have initiated this jet. If that parton is a gluon, then don't consider that jet. For finding the parton that initiated, there are a number of possibilities that @cbell1402 and @enibigir will decide on.

Possibilities:
* Use status codes to figure it out
* Use parentage information to figure it out
* Use momentum info. Maybe it's the highest momentum parton near the jet.

**Comment by cbell1402** [comment]
While selecting for partons that initiated a jet I discovered that sometimes the highest energy particles have more energy than the jet itself. This could be explained by "so-called out-of-cone losses." The below plots help explain that this is likely what is happening. 
![image](https://user-images.githubusercontent.com/93935192/213519344-c90e5c44-2b8c-435b-a430-fd0bf0e87725.png)
![image](https://user-images.githubusercontent.com/93935192/213519368-d1e590a8-caf8-4d61-b583-3a9e9d873494.png)
![image](https://user-images.githubusercontent.com/93935192/213519387-e0362ae3-7985-41ae-a4b3-2f4772e95cd4.png)

**Comment by cbell1402** [comment]
Script [loop.py](https://github.com/lawrenceleejr/FragmentationStudy/blob/63a211239b824f9a7dc24aeba37a18bb684c3f9a/loop.py) has been updated with gluon removal set for a delta_R < 0.4

**Comment by lawrenceleejr** [comment]
Beautiful. Let's go ahead and call this ticket closed!
