### ISSUE TITLE
Truth Jet Clustering

### ISSUE THREAD

**Issue by lawrenceleejr** [lawrenceleejr/FragmentationStudy#2]
We need to figure out how to get a jet particle multiplicity. The problem is, after you generate events in the MadGraph+Pythia chain, you just get particles out. So we need to cluster these into jets. We can cluster them directly using fast jet (the standard tool for doing this). There are even python bindings here: https://github.com/scikit-hep/fastjet

Or we can maybe just turn on Delphes in the MadGraph setup and that may produce "truth jets" which would be just clustered truth particles.

Once we have a collection of jets (by whatever method), we can ask each jet how many particles are in it (above some pT threshold or something). This will be our initial primary variable.

**Comment by cbell1402** [comment]
./DelphesHepMC2
eeToJJJ/Events/run_01/ ...hepmc.gz

**Comment by cbell1402** [comment]
Changes made to card
