### ISSUE TITLE
Make eeToZgamma sample

### ISSUE THREAD

**Issue by cbell1402** [lawrenceleejr/FragmentationStudy#5]
```
e+ e- > z a , (z > j j )
```
In run card: drjj = 1
In pythia card: guess

**Comment by cbell1402** [comment]
Made eeToZgamma sample with requested parameters. Used Delphes to obtain the .root file.

**Comment by lawrenceleejr** [comment]
@cbell1402 can you make a sample like this (ee -> z gamma) for a center of mass collision energy of 1 TeV with Pythia and then put the `hepmc` and the Delphes `.root` files into: `/userdata/FragmentationStudy/data/Pythia/`?

I think once we have that, we can close this ticket for now just to make some ticket progress. Related to #7

**Comment by cbell1402** [comment]
Moved the requested files
